#:import StoryCard uix.components.story_card
#:import StoryCard uix.components.page

<AScreen>:
    MDBoxLayout:
        md_bg_color: 1,0,0,1
        Page:
            name: "Sophie Cess"
            avatar: "../assets/images/darts.png"
            story: "../assets/images/story.png"
        # StoryCard:
        #     name: "Sophie Cess"
        #     avatar: "../assets/images/darts.png"
        #     story: "../assets/images/story.png"