#:import OnboardingItem uix.components.onboarding_item

<GameSettingsNumJumpsScreen>

    OnboardingItem:
        source: "../assets/images/setting_game/jump.jpg"
        text:
            "Select the number of jumps each player will be able to make"
        title: "Jumps limit"
        text_button_one: "3"
        text_button_two: "5"
        text_button_three: "10"
        group_name: "jump"
        callback: root.set_num_jumps


    