#:import GameSettingsContainer uix.components.game_settings_container

<GameSettingsNumPlayersScreen>

    GameSettingsContainer:
        source: "assets/images/game_settings/players.png"
        title: app.i18n._("GAMESETTINGS_TEAMS_NUMBER_TITLE") # "Teams number"
        text: app.i18n._("GAMESETTINGS_TEAMS_NUMBER_DESC") # "Select the number of teams, each team will be associated with a color"
        buttons: root.buttons