#:import StaticSwiper uix.components.static_swiper
#:import SWCard uix.components.sw_card


<GameCardContainer>:

    MDBoxLayout:
        orientation: "vertical"
        pos_hint: {"center_x": .5, "center_y": .5}

        StaticSwiper:
            id: swiper
            swipe_on_scroll: False
            padding: [dp(20), dp(40), dp(20), dp(40)]
            size_hint_y: None
            height: root.height
            width_mult: 1.3
