<TextTermsPolicy>
    orientation: "vertical"
    spacing: dp(12)
    size_hint_y: None
    height: "450dp"
    padding: [dp(10), dp(20), dp(10), dp(20)]
    ScrollView:
        do_scroll_x: False
        do_scroll_y: True
        MDLabel:
            id: label_dialog
            text: app_content_strings["terms_and_policies"]
            text_size: self.width, None
            size_hint: 1, None
            height: self.texture_size[1]
            markup: True
