<KMDCard@MDCard>:
    canvas.before:
        Color:
            rgba: self.md_bg_color[0], self.md_bg_color[1], self.md_bg_color[2], 0.4
        RoundedRectangle:
            pos: self.pos[0], self.pos[1] - 5
            size: self.size[0], self.size[1]
            radius: self.radius

    canvas:
        Color:
            rgba: self.md_bg_color
        RoundedRectangle:
            pos: self.pos[0], self.pos[1]
            size: self.size[0], self.size[1]
            radius: self.radius